### ISSUE TITLE
Some pools with swap volume return None for token weights

### ISSUE THREAD

**Issue by rbval** [balancer-labs/balancer-subgraph-v2#110]
Here's a pool that has swap volume but the weight between underlying tokens can't be determined.

Query:
```
{
  pools(where: {address: "0x06df3b2bbb68adc8b0e302443692037ed9f91b42"}) {
    id
    address
    totalWeight
    totalSwapVolume
    swapFee
    tokens {
      symbol
      weight
    }
  }
}
```

Should it be assumed that the weights are evenly split for these?

**Comment by TomAFrench** [comment]
Hi @rbval, thanks for your interest.

The `Pool` entity represents a number of different pool types so not all of the fields will be used by any given pool. The `weights` field is only used by `WeightedPools`, whereas we can't attach a meaningful value to this field for `Stable` and `Element` pools as the pricing rules are completely different. The decision was made that it was better to return null in this case than provide misleading synthetic weights.
