### ISSUE TITLE
Negative swapFee in FX Pool

### ISSUE THREAD

**Issue by markusbkoch** [balancer-labs/balancer-subgraph-v2#366]
Our frontend team noticed a strange case of negative swap fees in the pool snapshots of an FX Pool

https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-polygon-prune-v2-beta/graphql?query=%7B%0A++poolSnapshots%28%0A++++where%3A+%7B%0A++++++pool%3A+%220x726e324c29a1e49309672b244bdc4ff62a270407000200000000000000000702%22%2C%0A++++++timestamp_in%3A+%5B1675209600%2C+1675123200%5D%0A++++%7D%0A++++orderBy%3A+timestamp%0A++%29+%7B%0A++++pool+%7B%0A++++++id%0A++++%7D%0A++++timestamp%0A++++swapFees%0A++%7D%0A%7D

```
{
  "data": {
    "poolSnapshots": [
      {
        "pool": {
          "id": "0x726e324c29a1e49309672b244bdc4ff62a270407000200000000000000000702"
        },
        "timestamp": 1675123200,
        "swapFees": "4968.0412478600614"
      },
      {
        "pool": {
          "id": "0x726e324c29a1e49309672b244bdc4ff62a270407000200000000000000000702"
        },
        "timestamp": 1675209600,
        "swapFees": "4816.43323754945327"
      }
    ]
  }
}
```

See how the cumulative swapFees go down from ~5k to ~4.8k in a day.

This cumulative value is computed via a running sum here
https://github.com/balancer-labs/balancer-subgraph-v2/blob/56e73f943d0af53922916d6c548f3b87b9a3285e/src/mappings/vault.ts#L469

and `swapFeeUSD` for each swap is computed here
https://github.com/balancer-labs/balancer-subgraph-v2/blob/56e73f943d0af53922916d6c548f3b87b9a3285e/src/mappings/vault.ts#L427-L442

@schystz is this a known property of FX Pools, or is there maybe something wrong with the mapping?

**Comment by schystz** [comment]
Hi @markusbkoch, thanks for catching this and bringing our attention.

In short: yes this is a known property and we do not recommend changing the way we calculate it

Long Explanation:
The total fees should include the negative fees. The underlying concept behind our FX Invariant is that users will be charged a higher dynamic fees when they are trading beyond a specific region (beta region) and will also be given a rebate when they rebalance the pool back to the beta region.
Overall the fees collected from trading beyond the beta region will exceed the rebate paid out to traders to balance the pool. Do note that this rebate will be paid off using the accumulated fees from trading beyond the beta region. Ultimately the action of trading beyond the beta region and back will have an overall net gain in the total fees accumulated.
Overall, we do not advise to omit the negative fees computation from the total fees summation that we have derived as we consider the current calculation to be accurate and aligned with our own expectations

**Comment by markusbkoch** [comment]
Thank you for clarifying
